app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    #client: better-sqlite3
    #connection: ':memory:',
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DATABASE}
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

# auth:
#   # see https://backstage.io/docs/auth/ to learn about auth providers
#   providers:
#     # See https://backstage.io/docs/auth/guest/provider
#     guest: {}

auth:
  providers:
    guest: {}
      # userEntityRef: user:vpetkova
      # userEntityRef: user:default/ghristov

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Group, User]
  locations:
    # File locations are relative to the backend process, typically `packages/backend`
    #Groups
    - type: file
      target: ../../catalogs/groups/philips-labs.yaml

    - type: file
      target: ../../catalogs/groups/finance-team.yaml

    - type: file
      target: ../../catalogs/groups/identity-team.yaml

    # Systems
    - type: file
      target: ../../catalogs/systems/payments-system.yaml

    - type: file
      target: ../../catalogs/systems/user-management-system.yaml

    # Philips Labs repos
    - type: file
      target: ../../catalogs/tabia-catalog-info.yaml

    - type: file
      target: ../../catalogs/slsa-provenance-action-catalog-info.yaml

    - type: file
      target: ../../catalogs/fatt-catalog-info.yaml

    - type: file
      target: ../../catalogs/dct-notary-admin-catalog-info.yaml

    - type: file
      target: ../../catalogs/terraform-registry-catalog-info.yaml

    - type: file
      target: ../../catalogs/s3dl-catalog-info.yaml

    - type: file
      target: ../../catalogs/workflow-capability-catalog-info.yaml

    - type: file
      target: ../../catalogs/terraform-provider-cloudfoundry-catalog-info.yaml

    - type: file
      target: ../../catalogs/terraform-provider-unleash-catalog-info.yaml

    - type: file
      target: ../../catalogs/spiffe-vault-catalog-info.yaml

    # Users 
    - type: file
      target: ../../catalogs/users/vesela-catalog-info.yaml

    - type: file
      target: ../../catalogs/users/georgi-catalog-info.yaml

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]
  # Experimental: Always use the search method in UrlReaderProcessor.
  # New adopters are encouraged to enable it as this behavior will be the default in a future release.
  useUrlReadersSearch: true

kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

sonarcloud: 
  token: ${SONARCLOUD_TOKEN}
  organization: sep-arguspanoptes

techInsights:
  factRetrievers:
    sonarcloud-fact-retriever:  # Change from array to object
      enabled: true
      cadence: "*/1 * * * *" # Every hour
    dependabotFactRetriever:
      cadence: "*/2 * * * *" # every minute
      lifecycle: { timeToLive: { weeks: 2 } }
    githubAdvancedSecurityFactRetriever:
      cadence: "*/2 * * * *" # every minute
      lifecycle: { timeToLive: { weeks: 2 } }
  factChecker:
    checks:
      noHighBugsCheck:
        type: json-rules-engine
        name: No High Bugs Check
        description: Verifies that there are no high severity bugs
        factIds:
          - sonarcloud-fact-retriever
        rule:
          conditions:
            all:
              - fact: bugs
                operator: lessThanInclusive
                value: 0
      noHighCodeSmellsCheck:
        type: json-rules-engine
        name: Code Smells Check
        description: Verifies code smells are within acceptable range
        factIds:
          - sonarcloud-fact-retriever
        rule:
          conditions:
            all:
              - fact: code_smells
                operator: lessThanInclusive
                value: 20
      vulnerabilitiesCheck:
        type: json-rules-engine
        name: Vulnerabilities Check
        description: Verifies vulnerabilities are within acceptable range
        factIds:
          - sonarcloud-fact-retriever
        rule:
          conditions:
            all:
              - fact: vulnerabilities
                operator: lessThanInclusive
                value: 1 # change me
      qualityGateCheck:
        type: json-rules-engine
        name: Quality Gate Check
        description: Verifies quality gate status is passed
        factIds:
          - sonarcloud-fact-retriever
        rule:
          conditions:
            all:
              - fact: quality_gate
                operator: equal
                value: 'OK'
      codeCoverageCheck:
        type: json-rules-engine
        name: Code Coverage Check
        description: Verifies code coverage is within acceptable range
        factIds:
          - sonarcloud-fact-retriever
        rule:
          conditions:
            all:
              - fact: code_coverage
                operator: greaterThanInclusive
                value: 35
      dependabotLowAlertCheck:
        type: json-rules-engine
        name: Dependabot Alerts Below Threshold
        description: Checks if Dependabot alerts are below 5
        factIds:
          - dependabotFactRetriever
        rule:
          conditions:
            all:
              - fact: openAlertCount
                operator: lessThan
                value: 5
      githubCodeScanningCheck:
        type: json-rules-engine
        name: Code Scanning Alerts Below Threshold
        description: Checks if Code Scanning alerts are below acceptable threshold
        factIds:
          - githubAdvancedSecurityFactRetriever
        rule:
          conditions:
            all:
              - fact: openCodeScanningAlertCount
                operator: lessThan
                value: 5
      githubSecretScanningCheck:
        type: json-rules-engine
        name: No Secret Scanning Alerts
        description: Checks if there are no exposed secrets detected
        factIds:
          - githubAdvancedSecurityFactRetriever
        rule:
          conditions:
            all:
              - fact: openSecretScanningAlertCount
                operator: lessThanInclusive
                value: 0
      githubCodeScanningAlert:
        type: json-rules-engine
        name: Code Scanning Alerts as dictionary
        description: Checks if Code Scanning alerts are below acceptable threshold
        factIds:
          - githubAdvancedSecurityFactRetriever
        rule:
          conditions:
            all:
              - fact: codeScanningAlerts
                operator: equal
                value: {}
      githubSecretScanningAlert:
        type: json-rules-engine
        name: No Secret Scanning Alerts
        description: Checks if there are no exposed secrets detected
        factIds:
          - githubAdvancedSecurityFactRetriever
        rule:
          conditions:
            all:
              - fact: secretScanningAlerts
                operator: equal
                value: {}
      
