apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-app
  description: An example of a Backstage application.
  annotations:
    backstage.io/techdocs-ref: dir:.
  # links:
  #   - url: https://sonarcloud.io/project/overview?id=zofiarynkiewicz_tabia
  #     title: SonarCloud Analysis
  #     icon: check
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  system: backstage
  providesApis:
    - my-backstage-app