apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: payments-system
  title: Payments System
  annotations:
    dependabot/thresholds: '{"critical": 2, "high": 5, "medium": 15}'
  annotations:
    tech-insights.io/sonarcloud-quality-gate-red-threshold-percentage: '50'
    tech-insights.io/sonarcloud-quality-gate-yellow-threshold-percentage: '25'
    tech-insights.io/foundation-success-rate-threshold: '0'
    tech-insights.io/foundation-success-rate-operator: 'greaterThanInclusive'
    tech-insights.io/foundation-max-failures-threshold: '2'
    tech-insights.io/foundation-max-failures-operator: 'lessThanInclusive'
    tech-insights.io/preproduction-success-rate-threshold: '75'
    tech-insights.io/preproduction-success-rate-operator: 'greaterThanInclusive'
    tech-insights.io/preproduction-max-failures-threshold: '35'
    tech-insights.io/preproduction-max-failures-operator: 'lessThanInclusive'
spec:
  owner: finance-team
  members: [vpetkova]
