apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-management-system
  title: User Management System
  annotations:
    dependabot/thresholds: '{"critical": 99, "high": 99, "medium": 99}'
spec:
  owner: identity-team
  members: [ghristov]
