apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-management-system
  title: User Management System
  description: Manages user accounts, profiles, and authentication
  annotations:
    tech-insights.io/sonarcloud-bugs-threshold: '2'
    tech-insights.io/sonarcloud-bugs-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-smells-threshold: '30'
    tech-insights.io/sonarcloud-code-smells-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-coverage-threshold: '40'
    tech-insights.io/sonarcloud-code-coverage-operator: 'greaterThanInclusive'
    tech-insights.io/sonarcloud-quality-gate: 'OK'
    tech-insights.io/sonarcloud-quality-gate-operator: 'equal'
    tech-insights.io/foundation-success-rate-threshold: '100'
    tech-insights.io/foundation-success-rate-operator: 'greaterThanInclusive'
    tech-insights.io/foundation-max-failures-threshold: '2'
    tech-insights.io/foundation-max-failures-operator: 'lessThanInclusive'
    tech-insights.io/preproduction-success-rate-threshold: '70'
    tech-insights.io/preproduction-success-rate-operator: 'greaterThanInclusive'
    tech-insights.io/preproduction-max-failures-threshold: '35'
    tech-insights.io/preproduction-max-failures-operator: 'lessThanInclusive'
    
    # Github Advanced Security Annotations
    tech-insights.io/github-advanced-security-secrets-threshold: '0'
    tech-insights.io/github-advanced-security-secrets-operator: 'graterThan'

    tech-insights.io/github-advanced-security-critical-count-threshold: '0'
    tech-insights.io/github-advanced-security-critical-count-operator: 'greaterThan'

    tech-insights.io/github-advanced-security-high-count-threshold: '0'
    tech-insights.io/github-advanced-security-high-count-operator: 'greaterThan'

    tech-insights.io/github-advanced-security-medium-count-threshold: '5'
    tech-insights.io/github-advanced-security-medium-count-operator: 'greaterThan'

    tech-insights.io/github-advanced-security-low-count-threshold: '10'
    tech-insights.io/github-advanced-security-low-count-operator: 'greaterThan'
    
    # Thresholds for system
    github-advanced-security-system-critical-threshold-red: '0'
    github-advanced-security-system-secrets-threshold-red: '0'
    github-advanced-security-system-high-threshold-red: '0'
    github-advanced-security-system-medium-threshold-red: '0.5'
    github-advanced-security-system-medium-threshold-yellow: '0.1'
    github-advanced-security-system-low-threshold-yellow: '0.2'

    # Threshold for system with critical tag
    github-advanced-security-system-critical-critical-threshold-red: '0'
    github-advanced-security-system-critical-secrets-threshold-red: '0'
    github-advanced-security-system-critical-high-threshold-red: '0'
    github-advanced-security-system-critical-medium-threshold-red: '0.33'
    github-advanced-security-system-critical-med-threshold-yellow: '0.2'
    github-advanced-security-system-critical-low-threshold-yellow: '0.1'

    # Azure DevOps Annotations
    tech-insights.io/azure-bugs-threshold: '5'
    tech-insights.io/azure-bugs-operator: 'lessThanInclusive'
spec:
  owner: identity-team
  members: [ghristov]
