apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: user-management-system
  title: User Management System
  description: Manages user accounts, profiles, and authentication
  annotations:
    tech-insights.io/sonarcloud-bugs-threshold: '2'
    tech-insights.io/sonarcloud-bugs-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-smells-threshold: '30'
    tech-insights.io/sonarcloud-code-smells-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-coverage-threshold: '40'
    tech-insights.io/sonarcloud-code-coverage-operator: 'greaterThanInclusive'
    tech-insights.io/sonarcloud-quality-gate: 'OK'
    tech-insights.io/sonarcloud-quality-gate-operator: 'equal'
spec:
  owner: identity-team
  members: [ghristov]
