apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dct-notary-admin
  description: Adds the capability to manage your Docker Content Trust and notary certificates.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/dct-notary-admin
    backstage.io/source-location: url:https://github.com/philips-labs/dct-notary-admin
    sonarcloud.io/project-key: SEP-ArgusPanoptes_dct-notary-admin
    sonarcloud.io/enabled: 'true'
    tech-insights.io/sonarcloud-bugs-threshold: '0'
    tech-insights.io/sonarcloud-bugs-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-smells-threshold: '0'
    tech-insights.io/sonarcloud-code-smells-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-coverage-threshold: '0'
    tech-insights.io/sonarcloud-code-coverage-operator: 'greaterThanInclusive'
    tech-insights.io/sonarcloud-quality-gate: 'OK'
    tech-insights.io/sonarcloud-quality-gate-operator: 'equal'
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system
