apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dct-notary-admin
  description: Adds the capability to manage your Docker Content Trust and notary certificates.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/dct-notary-admin
    backstage.io/source-location: url:https://github.com/philips-labs/dct-notary-admin
    sonarcloud.io/project-key: SEP-ArgusPanoptes_dct-notary-admin
    sonarcloud.io/enabled: 'true'
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system

  workflowConfig:
    exclude:
      - 'Dependabot Updates'
