apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rustdesk
  description: This is another test repo.
  annotations:
    github.com/project-slug: rustdesk/rustdesk
    backstage.io/source-location: url:https://github.com/rustdesk/rustdesk
    azure.com/organization: argus-panoptes-dev
    azure.com/project: repo_2
    azure.com/bugs-query-id: b2fdb928-a73e-4cba-82c9-e605a194666d
    azure.com/pat: 9APDLq54nbzmerzTCuD50qLNWFHSprSivK7Q6zTuvqqP3PNMFPW0JQQJ99BDACAAAAAAAAAAAAASAZDOrt3M
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: rustdesk
  system: payments-system
