apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3dl
  description: Generates pre-signed S3 Download URLS for any key in the attached S3 bucket.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/s3dl
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/s3dl
    sonarcloud.io/project-key: SEP-ArgusPanoptes_s3dl
    sonarcloud.io/enabled: 'true'
    tech-insights.io/sonarcloud-bugs-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-code-smells-threshold: '0'
    tech-insights.io/sonarcloud-code-coverage-threshold: '0'
    tech-insights.io/sonarcloud-quality-gate: '1'
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system
