apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: slsa-provenance-action
  description: Implements the level 1 requirements of the SLSA framework.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/slsa-provenance-action
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/slsa-provenance-action
    sonarcloud.io/project-key: SEP-ArgusPanoptes_slsa-provenance-action
    sonarcloud.io/enabled: 'true'
    tech-insights.io/sonarcloud-bugs-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-code-smells-threshold: '0'
    tech-insights.io/sonarcloud-code-coverage-threshold: '0'
    tech-insights.io/sonarcloud-quality-gate: '1'
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system
