apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: slsa-provenance-action
  description: Implements the level 1 requirements of the SLSA framework.
  annotations:
    github.com/project-slug: philips-labs/slsa-provenance-action
    backstage.io/source-location: url:https://github.com/philips-labs/slsa-provenance-action
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: philips-labs
  system: payments-system
