apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: slsa-provenance-action
  description: Implements the level 1 requirements of the SLSA framework.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/slsa-provenance-action
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/slsa-provenance-action
    sonarcloud.io/project-key: SEP-ArgusPanoptes_slsa-provenance-action
    sonarcloud.io/enabled: 'true'
    pipeline/thresholds: '{"maxFailures": 2, "minSuccessRate": 95}'
    foundation/thresholds: '{"minSuccessRate": 95}'
    reporting/workflows: '["CodeQL", "Continuous Integration"]'
    preproduction/exclude: '["Dependabot Updates"]'
    azure.com/organization: argus-panoptes-dev
    azure.com/project: repo_2
    azure.com/bugs-query-id: b2fdb928-a73e-4cba-82c9-e605a194666d
    azure.com/pat: 9APDLq54nbzmerzTCuD50qLNWFHSprSivK7Q6zTuvqqP3PNMFPW0JQQJ99BDACAAAAAAAAAAAAASAZDOrt3M
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system

