apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spiffe-vault
  description: Integrates SPIFFE SVID authentication with Hashicorp Vault to retrieve a VAULT_TOKEN.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/spiffe-vault
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/spiffe-vault
    sonarcloud.io/project-key: SEP-ArgusPanoptes_spiffe-vault
    sonarcloud.io/enabled: 'true'
    tech-insights.io/sonarcloud-bugs-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-code-smells-threshold: '0'
    tech-insights.io/sonarcloud-code-coverage-threshold: '0'
    tech-insights.io/sonarcloud-quality-gate: '1'
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: payments-system
