apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-ai-alibaba
  description: This is another test repo.
  annotations:
    github.com/project-slug: alibaba/spring-ai-alibaba
    backstage.io/source-location: url:https://github.com/alibaba/spring-ai-alibaba
    reporting/workflows: '["CodeQL"]'
    azure.com/organization: argus-panoptes-dev
    azure.com/project: project_2
    azure.com/bugs-query-id: b2fdb928-a73e-4cba-82c9-e605a194666d
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: alibaba
  system: payments-system
