apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tabia
  description: Gives insights on the characteristics of our code bases.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/tabia
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/tabia
    sonarcloud.io/project-key: SEP-ArgusPanoptes_tabia
    sonarcloud.io/enabled: 'true'
    pipeline/thresholds: '{"maxFailures": 2, "minSuccessRate": 95}'
    foundation/thresholds: '{"minSuccessRate": 95}'
    reporting/workflows: '["CodeQL", "Continuous Integration"]'
    reporting/target-branch: develop
    preproduction/exclude: '["Dependabot.*"]'
    azure.com/organization: argus-panoptes-dev
    azure.com/project: project_2
    azure.com/bugs-query-id: b2fdb928-a73e-4cba-82c9-e605a194666d
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
