apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tabia
  description: Gives insights on the characteristics of our code bases.
  annotations:
    github.com/project-slug: philips-labs/tabia
    backstage.io/source-location: url:https://github.com/philips-labs/tabia
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: philips-labs
  system: user-management-system
