apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tabia
  description: Gives insights on the characteristics of our code bases.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/tabia
    backstage.io/source-location: url:https://github.com/philips-labs/tabia
    sonarcloud.io/project-key: SEP-ArgusPanoptes_tabia
    sonarcloud.io/enabled: 'true'
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
