apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tabia
  description: Gives insights on the characteristics of our code bases.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/tabia
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/tabia
    sonarcloud.io/project-key: SEP-ArgusPanoptes_tabia
    sonarcloud.io/enabled: 'true'
    pipeline/thresholds: '{"maxFailures": 2, "minSuccessRate": 95}'
    foundation/thresholds: '{"minSuccessRate": 95}'
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
  workflowConfig:
    exclude:
      - 'Dependabot Updates'
