apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-provider-unleash
  description: A Terraform provider to provision and manage Unleash admin resources.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/terraform-provider-unleash
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/terraform-provider-unleash
    sonarcloud.io/project-key: SEP-ArgusPanoptes_terraform-provider-unleash
    sonarcloud.io/enabled: 'true'
    pipeline/thresholds: '{"maxFailures": 2, "minSuccessRate": 95}'
    foundation/thresholds: '{"minSuccessRate": 95}'
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
  workflowConfig:
    exclude:
      - 'Dependabot Updates'
