apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-provider-cloudfoundry
  description: Allows you to configure a Cloud Foundry environment declaratively using HCL.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/terraform-provider-cloudfoundry
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/terraform-provider-cloudfoundry
    sonarcloud.io/project-key: SEP-ArgusPanoptes_terraform-provider-cloudfoundry
    sonarcloud.io/enabled: 'true'
    pipeline/thresholds: '{"maxFailures": 2, "minSuccessRate": 95}'
    foundation/thresholds: '{"minSuccessRate": 95}'
    reporting/workflows: '["CodeQL", "Continuous Integration"]'
    preproduction/exclude: '["Dependabot Updates"]'
    azure.com/organization: argus-panoptes-dev
    azure.com/project: project_1
    azure.com/bugs-query-id: 38d4d504-f147-45ce-9658-c27a9d3b9908
    azure.com/pat: 9APDLq54nbzmerzTCuD50qLNWFHSprSivK7Q6zTuvqqP3PNMFPW0JQQJ99BDACAAAAAAAAAAAAASAZDOrt3M
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system

