apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-provider-unleash
  description: A Terraform provider to provision and manage Unleash admin resources.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/terraform-provider-unleash
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/terraform-provider-unleash
    sonarcloud.io/project-key: SEP-ArgusPanoptes_terraform-provider-unleash
    sonarcloud.io/enabled: 'true'
    tech-insights.io/sonarcloud-bugs-threshold: '0'
    tech-insights.io/sonarcloud-bugs-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-vulnerabilities-threshold: '0'
    tech-insights.io/sonarcloud-vulnerabilities-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-smells-threshold: '0'
    tech-insights.io/sonarcloud-code-smells-operator: 'lessThanInclusive'
    tech-insights.io/sonarcloud-code-coverage-threshold: '0'
    tech-insights.io/sonarcloud-code-coverage-operator: 'greaterThanInclusive'
    tech-insights.io/sonarcloud-quality-gate: 'OK'
    tech-insights.io/sonarcloud-quality-gate-operator: 'equal'
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
