apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: trivy
  description: This is another test repo.
  annotations:
    github.com/project-slug: aquasecurity/trivy
    backstage.io/source-location: url:https://github.com/aquasecurity/trivy
    azure.com/organization: argus-panoptes-dev
    azure.com/project: project_2
    azure.com/bugs-query-id: b2fdb928-a73e-4cba-82c9-e605a194666d
    reporting/workflows: '["Auto-close issues", "Canary build"]'
  tags:
    - critical
spec:
  type: service
  lifecycle: experimental
  owner: aquasecurity
  system: user-management-system
