apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workflow-capability
  description: Allows caregivers and hospital management to start, control, and view the status of medical protocol workflows of patients.
  annotations:
    github.com/project-slug: SEP-ArgusPanoptes/workflow-capability
    backstage.io/source-location: url:https://github.com/SEP-ArgusPanoptes/workflow-capability
    sonarcloud.io/project-key: SEP-ArgusPanoptes_workflow-capability
    sonarcloud.io/enabled: 'true'
    pipeline/thresholds: '{"maxFailures": 2, "minSuccessRate": 95}'
    foundation/thresholds: '{"minSuccessRate": 95}'
  tags:
    - non-critical
spec:
  type: service
  lifecycle: experimental
  owner: SEP-ArgusPanoptes
  system: user-management-system
  workflowConfig:
    exclude:
      - 'Dependabot Updates'
